[package]
name = "melee_debug_ui"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
egui = { version = "0.36", default-features = false, features = ["default_fonts", "bytemuck"] }
bytemuck = "1.25"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
bindgen = "0.73"
